name: Build and Publish NuGet Package

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Build application
        run: dotnet build

      - name: Publish NuGet package
        run: dotnet nuget push Client\bin\Debug\Client.1.0.1.nupkg\Client.1.0.1.nupkg --source https://nuget.pkg.github.com/Jetus/index.json